### ISSUE TITLE
Kibana 6.4.0

### ISSUE THREAD

**Issue by gromit6891** [Gradiant/Kibana-style-plugin#3]
Will you be doing a release for Kibana 6.4.0? 

Just that there are no references to bundle custom css files in ui_app.jade for this version of Kibana.

**Comment by cgiraldo** [comment]
I will take a look to this version to see if a similar patch could be done

**Comment by cgiraldo** [comment]
I have updated the code to make it compatible with kibana 6.4.1.
Now the gradiant_style.style.css file must be include in th bootstrap/template.js.hbs file.

The sed command is:
`
sed -i "s/commons.style.css'),/commons.style.css'),createAnchor('{{bundlePath}}\/gradiant_style.style.css'),/g" /usr/share/kibana/src/ui/ui_render/bootstrap/template.js.hbs
`
